### ISSUE TITLE
Add more node labels to Neo config

### ISSUE THREAD

**Issue by dosumis** [obophenotype/bds-pipeline-config#5]
We should have Neo:labels for:

* Cluster (BDSHELP:Cluster)
* Gene (SO:...)
* Brain_region (UBERON:0002616)
* Taxon (Organism OBI:0100026)
* Morphology
* Projection type (once these are in place)
* Labels should also be added to individuals, making use of 'exemplar of' links.
* Add labels to individuals
    - e.g. exemplar_of some astrocyte. already done here? https://github.com/obophenotype/bds-pipeline-config/blob/add-BDSHELPexemplar_of-some/config/prod/neo4j2owl-config.yaml

- should be clear from inspection NEO (& OWL file if necessary) which Curies to use.

(leave out marker-based for now)

**Comment by shawntanzk** [comment]
@dosumis Added nodes I think are relevant, wonder if we do a BDS_subset that aren't neuronal - not sure how to write that in

@hkir-dev not sure if this needs to be merged somewhere or it's reading straight from the branch but tagging you in case this needs to be merged somewhere, in which case could you help me with that please? Thanks! 
https://github.com/obophenotype/bds-pipeline-config/blob/neo4jowl-config-edit/config/prod/neo4j2owl-config.yaml

**Comment by hkir-dev** [comment]
@shawntanzk we have an indentation problem at line 50. Can we check please?

**Comment by hkir-dev** [comment]
also couldn't found some of the entities (such as CL:4023012  and CL:4023038) in bdscratch-full.owl. So it crashes (I think)

**Comment by shawntanzk** [comment]
> @shawntanzk we have an indentation problem at line 50. Can we check please?

@hkir-dev whoops sorry, fixed it

> also couldn't found some of the entities (such as CL:4023012 and CL:4023038) in bdscratch-full.owl. So it crashes (I think)

Oh yeah, that's what I was worried about, those are newly added terms to CL-edit. I assume bdscratch-full.owl takes gets the CL terms from the current released CL
@dosumis can we do a CL release for this? alternatively I guess we can comment all the CL that aren't there yet for now?

**Comment by shawntanzk** [comment]
Added with work on branch done with #7 
see branch https://github.com/obophenotype/bds-pipeline-config/blob/add-BDSHELPexemplar_of-some/config/prod/neo4j2owl-config.yaml
